apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-demo
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cronjob-demo
        spec:
          imagePullSecrets: 
          - name: regcred 
          restartPolicy: Never
          containers:
          - name: cronjob-demo
            image: registry.cn-hangzhou.aliyuncs.com/jerryyuan/cronjob:v1
